### PR TITLE
v3: Fix InMemoryCache Clear() and LoadMany() concurrency bugs

### LINKED ISSUE #49: v1-v4: LoadMany() returns in non-deterministic order
In `v1-v4` of this library, `LoadMany()` does not return in deterministic order. That is, a call to `LoadMany("A", "B")` can give results `[ResultA, ResultB]`.

To reproduce, run the unit tests multiple times:
```
$ go test -count=1000 .
--- FAIL: TestLoader (0.00s)
    --- FAIL: TestLoader/test_LoadMany_returns_len(errors)_==_len(keys) (0.02s)
        dataloader_test.go:103: Expected an error on the first item loaded
        dataloader_test.go:107: Expected second and third errors to be nil
--- FAIL: TestLoader (0.00s)
    --- FAIL: TestLoader/test_LoadMany_returns_len(errors)_==_len(keys) (0.02s)
        dataloader_test.go:103: Expected an error on the first item loaded
        dataloader_test.go:107: Expected second and third errors to be nil
--- FAIL: TestLoader (0.00s)
    --- FAIL: TestLoader/test_LoadMany_returns_len(errors)_==_len(keys) (0.02s)
        dataloader_test.go:103: Expected an error on the first item loaded
        dataloader_test.go:107: Expected second and third errors to be nil
--- FAIL: TestLoader (0.00s)
    --- FAIL: TestLoader/test_LoadMany_returns_len(errors)_==_len(keys) (0.02s)
        dataloader_test.go:103: Expected an error on the first item loaded
        dataloader_test.go:107: Expected second and third errors to be nil
--- FAIL: TestLoader (0.00s)
    --- FAIL: TestLoader/test_LoadMany_returns_len(errors)_==_len(keys) (0.02s)
        dataloader_test.go:103: Expected an error on the first item loaded
        dataloader_test.go:107: Expected second and third errors to be nil
--- FAIL: TestLoader (0.00s)
    --- FAIL: TestLoader/test_LoadMany_returns_len(errors)_==_len(keys) (0.02s)
        dataloader_test.go:103: Expected an error on the first item loaded
        dataloader_test.go:107: Expected second and third errors to be nil
```

It seems like the cause may be the `thunk` creation happens concurrently in a goroutine, so the batch of keys passed to the batch function may end up out of order.

### PR DESCRIPTION
**Pull request by tonyghita**
Fixes #49 and #51. This is the same as fixes for the v2 branch merged in #53 and #54, but in one pull-request.

I'll make the same change for v4, and then just apply the cache Clear() fix to v5.

### CODE REVIEW

File: dataloader.go [hunk 1]
```diff
@@ -277,14 +277,17 @@ func (l *Loader) LoadMany(originalContext context.Context, keys []string) ThunkM
 	wg := sync.WaitGroup{}
 
 	wg.Add(length)
-	for i := range keys {
-		go func(ctx context.Context, i int) {
+	for i, key := range keys {
+		// Request the key serially to ensure the result order is maintained in key order.
+		thunk := l.Load(ctx, key)
```
Comment (nicksrandall) [inline dataloader.go]: Do we need this change on this version? If the index is being passed to the `go func` then the order of the results should be correct. Am I missing something?

Comment (nicksrandall) [reply dataloader.go]: That said, I don't think this change hurts anything so I'll approve.

Comment (tonyghita) [reply dataloader.go]: It might not be needed in this version, I might've got the cache Clear issues crossed with the non-deterministic LoadMany issue from the earlier versions.

**Comment by tonyghita** [comment]
Thanks for all the reviews @nicksrandall!
